version: '3.8'

services:
  inedodb:
    image: proget.inedo.com/productimages/inedo/inedodb:17.6
    container_name: inedodb
    restart: unless-stopped
    volumes:
      - ./proget-postgres-data:/var/lib/inedodb
    networks:
      - repo-network

  proget:
    depends_on:
      - inedodb
    image: proget.inedo.com/productimages/inedo/proget:latest
    container_name: proget
    restart: unless-stopped
    ports:
      - "8624:80"
    environment:
      - TZ=Europe/Warsaw
      - PROGET_POSTGRES_CONNECTION_STRING=Host=inedodb;Port=5432;Database=proget;Username=inedodb;Password=BvSTd940qjCgw32KT0jH5nadCqLstt8w;SSL Mode=Disable;Trust Server Certificate=true
    volumes:
      - ./proget-packages:/var/proget/packages
      - ./proget-database:/var/proget/database
      - ./proget-backups:/var/proget/backups
      - ./proget-extensions:/var/proget/extensions
    networks:
      - repo-network

  # Sonatype Nexus Repository
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: unless-stopped
    ports:
      - "8081:8081"  # Nexus web interface
    volumes:
      - ./nexus-data:/nexus-data
    environment:
      - INSTALL4J_ADD_VM_PARAMS=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g
    networks:
      - repo-network

networks:
  repo-network:
    driver: bridge