// <auto-generated/>
// Generator Build: 2025-09-13 21:38:59 UTC
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using FastFsm.Contracts;
using FastFsm.Runtime;

public interface IDeepHierarchyMachine : IStateMachineSync<HsmState, HsmTrigger> { }

public partial class DeepHierarchyMachine : StateMachineBase<HsmState, HsmTrigger>, IDeepHierarchyMachine {
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    partial void OnActionException(string context, System.Exception ex);

    public DeepHierarchyMachine(HsmState initialState) : base(initialState) {
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    protected override bool TryFireInternal(HsmTrigger trigger, object? payload) {
        return false; // No transitions defined
    }
    /// <summary>
    /// Checks if the specified trigger can be fired in the current state (runtime evaluation including guards)
    /// </summary>
    /// <param name="trigger">The trigger to check</param>
    /// <returns>True if the trigger can be fired, false otherwise</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    protected override bool CanFireInternal(HsmTrigger trigger) {
        switch (_currentState) {
            default: return false;
        }
    }

    /// <summary>
    /// Gets the list of triggers that can be fired in the current state (runtime evaluation including guards)
    /// </summary>
    /// <returns>List of triggers that can be fired in the current state</returns>
    protected override System.Collections.Generic.IReadOnlyList<HsmTrigger> GetPermittedTriggersInternal() {
        switch (_currentState) {
            case HsmState.Completed: return System.Array.Empty<HsmTrigger>();
            case HsmState.Error: return System.Array.Empty<HsmTrigger>();
            case HsmState.Idle: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Cleanup: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Initializing: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Processing: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Processing_Computing: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Processing_Computing_Calculating: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Processing_Computing_Loading: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Processing_Computing_Storing: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Processing_Reading: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Processing_Writing: return System.Array.Empty<HsmTrigger>();
            case HsmState.Working_Validating: return System.Array.Empty<HsmTrigger>();
            default: return System.Array.Empty<HsmTrigger>();
        }
    }

}

/*
====== PARSER COMPARISON DEBUG INFO ======
Original StateMachineParser Model:
{
  "Namespace": "",
  "ClassName": "DeepHierarchyMachine",
  "ContainerClasses": [],
  "StateType": "HsmState",
  "TriggerType": "HsmTrigger",
  "Transitions": [],
  "States": {
    "Idle": {
      "Name": "Idle",
      "OrdinalValue": 0,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working": {
      "Name": "Working",
      "OrdinalValue": 1,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Completed": {
      "Name": "Completed",
      "OrdinalValue": 2,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Error": {
      "Name": "Error",
      "OrdinalValue": 3,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Initializing": {
      "Name": "Working_Initializing",
      "OrdinalValue": 4,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Processing": {
      "Name": "Working_Processing",
      "OrdinalValue": 5,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Validating": {
      "Name": "Working_Validating",
      "OrdinalValue": 6,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Cleanup": {
      "Name": "Working_Cleanup",
      "OrdinalValue": 7,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Processing_Reading": {
      "Name": "Working_Processing_Reading",
      "OrdinalValue": 8,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Processing_Computing": {
      "Name": "Working_Processing_Computing",
      "OrdinalValue": 9,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Processing_Writing": {
      "Name": "Working_Processing_Writing",
      "OrdinalValue": 10,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Processing_Computing_Loading": {
      "Name": "Working_Processing_Computing_Loading",
      "OrdinalValue": 11,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Processing_Computing_Calculating": {
      "Name": "Working_Processing_Computing_Calculating",
      "OrdinalValue": 12,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "Working_Processing_Computing_Storing": {
      "Name": "Working_Processing_Computing_Storing",
      "OrdinalValue": 13,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    }
  },
  "GenerationConfig": {
    "HasOnEntryExit": false,
    "HasPayload": false,
    "HasExtensions": false,
    "IsAsync": false,
    "TreatCancellationAsFailure": false
  },
  "TriggerPayloadTypes": {},
  "GenerateLogging": false,
  "GenerateDependencyInjection": false,
  "EmitStructuralHelpers": false,
  "ContinueOnCapturedContext": false,
  "ParentOf": {},
  "ChildrenOf": {},
  "Depth": {},
  "InitialChildOf": {},
  "HistoryOf": {},
  "HierarchyEnabled": false,
  "HasHierarchy": false,
  "UsedEnumOnlyFallback": true
}

FluentParser Model:
{}
==========================================
*/