<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>


  <ItemGroup>
    <Compile Include="..\FastFsm\Runtime\Extensions\ExtensionRunner.cs" Link="Runtime/Extensions/ExtensionRunner.cs" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\FastFsm\FastFsm.csproj" />
  </ItemGroup>

</Project>
