<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FastFsm.Net" Version="0.0.0.7-fluentrefinement" />
	</ItemGroup>




  <ItemGroup>
    <Compile Include="..\FastFsm\Runtime\Extensions\ExtensionRunner.cs" Link="Runtime/Extensions/ExtensionRunner.cs" />
  </ItemGroup>

</Project>
