<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    
    <!-- Enable source generator debugging output -->
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)\GeneratedFiles</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Abstractions\Abstractions.csproj" />
    <ProjectReference Include="..\FastFsm\FastFsm.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="xunit" Version="2.7.0" />
    <ProjectReference Include="..\\Generator\\Generator.csproj" 
                      OutputItemType="Analyzer" 
                      ReferenceOutputAssembly="false" />
    <ProjectReference Include="..\\Generator.Model\\Generator.Model.csproj" 
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" 
                      PrivateAssets="all" />
    <ProjectReference Include="..\\Generator.Rules\\Generator.Rules.csproj" 
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" 
                      PrivateAssets="all" />
    <ProjectReference Include="..\\Generator.Logger\\Generator.Logger.csproj" 
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" 
                      PrivateAssets="all" />
    <ProjectReference Include="..\\IndentedStringBuilder\\IndentedStringBuilder.csproj" 
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" 
                      PrivateAssets="all" />
    <ProjectReference Include="..\\Generator.DependencyInjection\\Generator.DependencyInjection.csproj" 
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false" 
                      PrivateAssets="all" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.7">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <Target Name="CleanGeneratedFiles" BeforeTargets="Clean">
    <RemoveDir Directories="$(CompilerGeneratedFilesOutputPath)" />
  </Target>

</Project>
