using Xunit;
using Abstractions.Attributes;
using System.Threading.Tasks;
using Dsl;

namespace ParserComparison.Tests
{
    public partial class TinyAsyncHsm_Comparison
    {
        // Legacy Attributes version
        [StateMachine(typeof(S), typeof(T), EnableHierarchy = true)]
        public partial class TinyAsyncHsm_Attributes
        {
            public enum S { Outside, Menu, Menu_Item }
            public enum T { Enter }
            // Parent with shallow history; initial child
            [State(S.Menu, History = HistoryMode.Shallow, OnEntry = nameof(OnMenuEntryAsync))]
            [State(S.Menu_Item, Parent = S.Menu, IsInitial = true)]
            private void ConfigureStates() { }

            // Simple external transition, no actions
            [Transition(S.Outside, T.Enter, S.Menu)]
            private void ConfigureTransitions() { }

            // Async OnEntry to force async machine variant
            private ValueTask OnMenuEntryAsync() => ValueTask.CompletedTask;
        }

        // Fluent API version
        [StateMachine(typeof(S), typeof(T), EnableHierarchy = true)]
        public partial class TinyAsyncHsm_Fluent
        {
            public enum S { Outside, Menu, Menu_Item }
            public enum T { Enter }
            
            private static void Configure()
            {
                // Parent with shallow history and initial child
                FSM.State(S.Menu)
                    .HistoryShallow()
                    .OnEntryAsync(nameof(OnMenuEntryAsync))
                    .Initial(S.Menu_Item);
                    
                FSM.State(S.Menu_Item)
                    .ChildOf(S.Menu);
                
                FSM.State(S.Outside);
                
                // Simple external transition
                FSM.At(S.Outside)
                    .On(T.Enter)
                    .GoTo(S.Menu);
            }

            // Async OnEntry to force async machine variant
            private ValueTask OnMenuEntryAsync() => ValueTask.CompletedTask;
        }
        
        [Fact]
        public void TinyAsyncHsm_Models_Should_Match()
        {
            // This test will help us compare the models generated by both parsers
            // When it compiles, we can inspect the generated code to see differences
            Assert.True(true, "Models comparison placeholder");
        }
    }
}