// <auto-generated/>
// Generator Build: 2025-08-30 16:07:20 UTC
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using FastFsm.Contracts;
using FastFsm.Runtime;

public interface IDoorMachine : IStateMachineSync<DoorState, DoorTrigger> { }

public partial class DoorMachine : StateMachineBase<DoorState, DoorTrigger>, IDoorMachine {
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    partial void OnActionException(string context, System.Exception ex);

    public DoorMachine(DoorState initialState) : base(initialState) {
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    protected override bool TryFireInternal(DoorTrigger trigger, object? payload) {
        return false; // No transitions defined
    }
    /// <summary>
    /// Checks if the specified trigger can be fired in the current state (runtime evaluation including guards)
    /// </summary>
    /// <param name="trigger">The trigger to check</param>
    /// <returns>True if the trigger can be fired, false otherwise</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    protected override bool CanFireInternal(DoorTrigger trigger) {
        switch (_currentState) {
            default: return false;
        }
    }

    /// <summary>
    /// Gets the list of triggers that can be fired in the current state (runtime evaluation including guards)
    /// </summary>
    /// <returns>List of triggers that can be fired in the current state</returns>
    protected override System.Collections.Generic.IReadOnlyList<DoorTrigger> GetPermittedTriggersInternal() {
        switch (_currentState) {
            case DoorState.Closed: return System.Array.Empty<DoorTrigger>();
            case DoorState.Locked: return System.Array.Empty<DoorTrigger>();
            case DoorState.Opened: return System.Array.Empty<DoorTrigger>();
            default: return System.Array.Empty<DoorTrigger>();
        }
    }

}
