// <auto-generated/>
// FastFSM Discovery Dump
// This file lists all discovered [StateMachine] candidates

internal static class __FastFsm_DiscoveryDump
{
    // Total candidates discovered: 1
    // Valid: 1, Skipped: 0
    // Format: Index | FullyQualifiedName | Status | SkipReason

    // 0: TestMachine
    //     status=VALID

    /*
     * End of discovery dump
     */
}
