// <auto-generated/>
// Generator Build: 2025-08-30 17:28:57 UTC
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using FastFsm.Contracts;
using FastFsm.Runtime;
using Microsoft.Extensions.Logging;
using TestMachines;

namespace TestMachines {
    public interface ILifecycleTestMachine : IStateMachineSync<State, Trigger> { }

    public partial class LifecycleTestMachine : StateMachineBase<State, Trigger>, ILifecycleTestMachine {
        private readonly ILogger<LifecycleTestMachine>? _logger;
        private readonly string _instanceId = Guid.NewGuid().ToString();

        // State and trigger name arrays for zero-allocation logging
        private static readonly string[] s_stateNames = new string[] { "Initial", "Processing", "Completed", "Failed"         };
                [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                private static string NameOf(State s) {
                    int index = (int)s;
                    return (index >= 0 && index < s_stateNames.Length) ? s_stateNames[index] : (index == -1 ? "<root>" : s.ToString());
                }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        partial void OnActionException(string context, System.Exception ex);

        public LifecycleTestMachine(State initialState, ILogger<LifecycleTestMachine>? logger = null) : base(initialState) {
            _logger = logger;
        }

        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        protected override bool TryFireInternal(Trigger trigger, object? payload) {
            return false; // No transitions defined
        }
        /// <summary>
        /// Checks if the specified trigger can be fired in the current state (runtime evaluation including guards)
        /// </summary>
        /// <param name="trigger">The trigger to check</param>
        /// <returns>True if the trigger can be fired, false otherwise</returns>
        [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        protected override bool CanFireInternal(Trigger trigger) {
            switch (_currentState) {
                default: return false;
            }
        }

        /// <summary>
        /// Gets the list of triggers that can be fired in the current state (runtime evaluation including guards)
        /// </summary>
        /// <returns>List of triggers that can be fired in the current state</returns>
        protected override System.Collections.Generic.IReadOnlyList<Trigger> GetPermittedTriggersInternal() {
            switch (_currentState) {
                case State.Completed: return System.Array.Empty<Trigger>();
                case State.Failed: return System.Array.Empty<Trigger>();
                case State.Initial: return System.Array.Empty<Trigger>();
                case State.Processing: return System.Array.Empty<Trigger>();
                default: return System.Array.Empty<Trigger>();
            }
        }

    }
}
