// <auto-generated/>
#nullable enable
using Microsoft.Extensions.Logging;
using System;

namespace TestMachines {
    /// <summary>
    /// High-performance logging for LifecycleTestMachine state machine
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("StateMachineGenerator", "1.0.0")]
    internal static class LifecycleTestMachineLog {
        // Static LoggerMessage.Define delegates for zero-allocation logging
        // UnhandledTrigger
        private static readonly Action<ILogger, string, string, string, Exception?> s_UnhandledTrigger = LoggerMessage.Define<string, string, string>(
            LogLevel.Warning,
            new EventId(1100, nameof(UnhandledTrigger)),
            "State machine {InstanceId} unhandled trigger: {Trigger} in state {State}");

        // MachineStarted
        private static readonly Action<ILogger, string, string, Exception?> s_MachineStarted = LoggerMessage.Define<string, string>(
            LogLevel.Information,
            new EventId(1101, nameof(MachineStarted)),
            "State machine {InstanceId} started at {InitialState}");

        // MachineStopped
        private static readonly Action<ILogger, string, string, Exception?> s_MachineStopped = LoggerMessage.Define<string, string>(
            LogLevel.Information,
            new EventId(1102, nameof(MachineStopped)),
            "State machine {InstanceId} stopped at {FinalState}");

        // TransitionStarted
        private static readonly Action<ILogger, string, string, string, string, Exception?> s_TransitionStarted = LoggerMessage.Define<string, string, string, string>(
            LogLevel.Debug,
            new EventId(1103, nameof(TransitionStarted)),
            "State machine {InstanceId} transition started: {FromState} --({Trigger})--> {ToState}");

        // AsyncActionStarted
        private static readonly Action<ILogger, string, string, string, Exception?> s_AsyncActionStarted = LoggerMessage.Define<string, string, string>(
            LogLevel.Debug,
            new EventId(1104, nameof(AsyncActionStarted)),
            "State machine {InstanceId} async action started: {ActionName} (on {Context})");

        // AsyncActionCompleted
        private static readonly Action<ILogger, string, string, string, double, Exception?> s_AsyncActionCompleted = LoggerMessage.Define<string, string, string, double>(
            LogLevel.Debug,
            new EventId(1105, nameof(AsyncActionCompleted)),
            "State machine {InstanceId} async action completed: {ActionName} (on {Context}) in {ElapsedMs}ms");

        // AsyncActionFailed
        private static readonly Action<ILogger, string, string, string, string, Exception?> s_AsyncActionFailed = LoggerMessage.Define<string, string, string, string>(
            LogLevel.Warning,
            new EventId(1106, nameof(AsyncActionFailed)),
            "State machine {InstanceId} async action failed: {ActionName} (on {Context}) error: {ErrorType}");

        // CallbackException
        private static readonly Action<ILogger, string, string, string, string, Exception?> s_CallbackException = LoggerMessage.Define<string, string, string, string>(
            LogLevel.Warning,
            new EventId(1107, nameof(CallbackException)),
            "State machine {InstanceId} {CallbackKind} threw: {CallbackName} (on {Context})");

        private static readonly Action<ILogger, string, string, string, string, Exception?> s_TransitionSucceeded = LoggerMessage.Define<string, string, string, string>(
            LogLevel.Information,
            new EventId(1, nameof(TransitionSucceeded)),
            "State machine {InstanceId} transitioned from {FromState} to {ToState} on trigger {Trigger}");

        private static readonly Action<ILogger, string, string, string, string, string, Exception?> s_GuardFailed = LoggerMessage.Define<string, string, string, string, string>(
            LogLevel.Warning,
            new EventId(2, nameof(GuardFailed)),
            "State machine {InstanceId} guard {GuardName} prevented transition from {FromState} to {ToState} on trigger {Trigger}");

        private static readonly Action<ILogger, string, string, string, Exception?> s_TransitionFailed = LoggerMessage.Define<string, string, string>(
            LogLevel.Warning,
            new EventId(3, nameof(TransitionFailed)),
            "State machine {InstanceId} failed to transition from {FromState} on trigger {Trigger} - no valid transition found");

        private static readonly Action<ILogger, string, string, string, Exception?> s_OnEntryExecuted = LoggerMessage.Define<string, string, string>(
            LogLevel.Debug,
            new EventId(4, nameof(OnEntryExecuted)),
            "State machine {InstanceId} executed OnEntry {MethodName} for state {State}");

        private static readonly Action<ILogger, string, string, string, Exception?> s_OnExitExecuted = LoggerMessage.Define<string, string, string>(
            LogLevel.Debug,
            new EventId(5, nameof(OnExitExecuted)),
            "State machine {InstanceId} executed OnExit {MethodName} for state {State}");

        private static readonly Action<ILogger, string, string, string, string, string, Exception?> s_ActionExecuted = LoggerMessage.Define<string, string, string, string, string>(
            LogLevel.Debug,
            new EventId(6, nameof(ActionExecuted)),
            "State machine {InstanceId} executed action {ActionName} during transition from {FromState} to {ToState} on trigger {Trigger}");

        private static readonly Action<ILogger, string, string, string, string, Exception?> s_PayloadValidationFailed = LoggerMessage.Define<string, string, string, string>(
            LogLevel.Warning,
            new EventId(7, nameof(PayloadValidationFailed)),
            "State machine {InstanceId} payload validation failed for trigger {Trigger} - expected {ExpectedType}, got {ActualType}");

        private static readonly Action<ILogger, string, string, string, string, Exception?> s_InternalTransitionOnAncestor = LoggerMessage.Define<string, string, string, string>(
            LogLevel.Debug,
            new EventId(10, nameof(InternalTransitionOnAncestor)),
            "State machine {InstanceId} internal transition on ancestor {AncestorState} from state {CurrentState} on trigger {Trigger}");

        private static readonly Action<ILogger, string, string, string, string, int, int, Exception?> s_HierarchicalTransition = LoggerMessage.Define<string, string, string, string, int, int>(
            LogLevel.Debug,
            new EventId(11, nameof(HierarchicalTransition)),
            "State machine {InstanceId} hierarchical transition from {FromState} to {ToState} via LCA {LcaState} - exiting {ExitCount} states, entering {EntryCount} states");

        private static readonly Action<ILogger, string, string, string, string, Exception?> s_CompositeStateEntry = LoggerMessage.Define<string, string, string, string>(
            LogLevel.Debug,
            new EventId(12, nameof(CompositeStateEntry)),
            "State machine {InstanceId} entering composite state {CompositeState}, resolved to {ResolvedTarget} using {ResolutionMethod}");

        private static readonly Action<ILogger, string, string, string, string, Exception?> s_HistoryRestored = LoggerMessage.Define<string, string, string, string>(
            LogLevel.Debug,
            new EventId(13, nameof(HistoryRestored)),
            "State machine {InstanceId} restored {HistoryType} history for composite {CompositeState} to state {RestoredState}");

        private static readonly Action<ILogger, string, string, Exception?> s_ActivePath = LoggerMessage.Define<string, string>(
            LogLevel.Trace,
            new EventId(14, nameof(ActivePath)),
            "State machine {InstanceId} active path: {Path}");

        /// <summary>
        /// Logs successful state transition
        /// </summary>
        public static void TransitionSucceeded(ILogger? logger, string instanceId, string fromState, string toState, string trigger) {
            if (logger?.IsEnabled(LogLevel.Information) == true) {
                s_TransitionSucceeded(logger, instanceId, fromState, toState, trigger, null);
            }
        }

        /// <summary>
        /// Logs when guard prevents transition
        /// </summary>
        public static void GuardFailed(ILogger? logger, string instanceId, string guardName, string fromState, string toState, string trigger) {
            if (logger?.IsEnabled(LogLevel.Warning) == true) {
                s_GuardFailed(logger, instanceId, guardName, fromState, toState, trigger, null);
            }
        }

        /// <summary>
        /// Logs when no valid transition found
        /// </summary>
        public static void TransitionFailed(ILogger? logger, string instanceId, string fromState, string trigger) {
            if (logger?.IsEnabled(LogLevel.Warning) == true) {
                s_TransitionFailed(logger, instanceId, fromState, trigger, null);
            }
        }

        /// <summary>
        /// Logs OnEntry method execution
        /// </summary>
        public static void OnEntryExecuted(ILogger? logger, string instanceId, string methodName, string state) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_OnEntryExecuted(logger, instanceId, methodName, state, null);
            }
        }

        /// <summary>
        /// Logs OnExit method execution
        /// </summary>
        public static void OnExitExecuted(ILogger? logger, string instanceId, string methodName, string state) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_OnExitExecuted(logger, instanceId, methodName, state, null);
            }
        }

        /// <summary>
        /// Logs action execution during transition
        /// </summary>
        public static void ActionExecuted(ILogger? logger, string instanceId, string actionName, string fromState, string toState, string trigger) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_ActionExecuted(logger, instanceId, actionName, fromState, toState, trigger, null);
            }
        }

        /// <summary>
        /// Logs payload validation failure
        /// </summary>
        public static void PayloadValidationFailed(ILogger? logger, string instanceId, string trigger, string expectedType, string actualType) {
            if (logger?.IsEnabled(LogLevel.Warning) == true) {
                s_PayloadValidationFailed(logger, instanceId, trigger, expectedType, actualType, null);
            }
        }

        /// <summary>
        /// Logs internal transition executed on ancestor state
        /// </summary>
        public static void InternalTransitionOnAncestor(ILogger? logger, string instanceId, string ancestorState, string currentState, string trigger) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_InternalTransitionOnAncestor(logger, instanceId, ancestorState, currentState, trigger, null);
            }
        }

        /// <summary>
        /// Logs hierarchical transition with LCA information
        /// </summary>
        public static void HierarchicalTransition(ILogger? logger, string instanceId, string fromState, string toState, string lcaState, int exitCount, int entryCount) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_HierarchicalTransition(logger, instanceId, fromState, toState, lcaState, exitCount, entryCount, null);
            }
        }

        /// <summary>
        /// Logs entry into composite state with resolution
        /// </summary>
        public static void CompositeStateEntry(ILogger? logger, string instanceId, string compositeState, string resolvedTarget, string resolutionMethod) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_CompositeStateEntry(logger, instanceId, compositeState, resolvedTarget, resolutionMethod, null);
            }
        }

        /// <summary>
        /// Logs history restoration
        /// </summary>
        public static void HistoryRestored(ILogger? logger, string instanceId, string historyType, string compositeState, string restoredState) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_HistoryRestored(logger, instanceId, historyType, compositeState, restoredState, null);
            }
        }

        /// <summary>
        /// Logs the active state path
        /// </summary>
        public static void ActivePath(ILogger? logger, string instanceId, string path) {
            if (logger?.IsEnabled(LogLevel.Trace) == true) {
                s_ActivePath(logger, instanceId, path, null);
            }
        }

        /// <summary>
        /// Logs unhandled triggers
        /// </summary>
        public static void UnhandledTrigger(ILogger? logger, string instanceId, string state, string trigger) {
            if (logger?.IsEnabled(LogLevel.Warning) == true) {
                s_UnhandledTrigger(logger, instanceId, trigger, state, null);
            }
        }

        /// <summary>
        /// Logs when state machine starts
        /// </summary>
        public static void MachineStarted(ILogger? logger, string instanceId, string initialState) {
            if (logger?.IsEnabled(LogLevel.Information) == true) {
                s_MachineStarted(logger, instanceId, initialState, null);
            }
        }

        /// <summary>
        /// Logs when state machine stops
        /// </summary>
        public static void MachineStopped(ILogger? logger, string instanceId, string finalState) {
            if (logger?.IsEnabled(LogLevel.Information) == true) {
                s_MachineStopped(logger, instanceId, finalState, null);
            }
        }

        /// <summary>
        /// Logs when transition starts
        /// </summary>
        public static void TransitionStarted(ILogger? logger, string instanceId, string fromState, string trigger, string toState) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_TransitionStarted(logger, instanceId, fromState, trigger, toState, null);
            }
        }

        /// <summary>
        /// Logs when async action starts
        /// </summary>
        public static void AsyncActionStarted(ILogger? logger, string instanceId, string actionName, string context) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_AsyncActionStarted(logger, instanceId, actionName, context, null);
            }
        }

        /// <summary>
        /// Logs when async action completes
        /// </summary>
        public static void AsyncActionCompleted(ILogger? logger, string instanceId, string actionName, string context, double elapsedMs) {
            if (logger?.IsEnabled(LogLevel.Debug) == true) {
                s_AsyncActionCompleted(logger, instanceId, actionName, context, elapsedMs, null);
            }
        }

        /// <summary>
        /// Logs when async action fails
        /// </summary>
        public static void AsyncActionFailed(ILogger? logger, string instanceId, string actionName, string context, Exception ex) {
            if (logger?.IsEnabled(LogLevel.Warning) == true) {
                s_AsyncActionFailed(logger, instanceId, actionName, context, ex.GetType().Name, ex);
            }
        }

        /// <summary>
        /// Logs when callback throws exception
        /// </summary>
        public static void CallbackException(ILogger? logger, string instanceId, string kind, string callbackName, string context, Exception ex) {
            if (logger?.IsEnabled(LogLevel.Warning) == true) {
                s_CallbackException(logger, instanceId, kind, callbackName, context, ex);
            }
        }

    }
}
