// <auto-generated/>
// FastFSM Discovery Dump
// This file lists all discovered [StateMachine] candidates

internal static class __FastFsm_DiscoveryDump
{
    // Total candidates discovered: 2
    // Valid: 0, Skipped: 2
    // Format: Index | FullyQualifiedName | Status | SkipReason

    // 0: TestMachines.ContinueOnEntryMachine_Fluent
    //     status=SKIPPED
    //     reason=No [StateMachine] attribute

    // 1: TestMachines.ThrowingActionMachine_Fluent
    //     status=SKIPPED
    //     reason=No [StateMachine] attribute

    /*
     * End of discovery dump
     */
}
