// <auto-generated/>
// FastFSM Discovery Dump
// This file lists all discovered [StateMachine] candidates

internal static class __FastFsm_DiscoveryDump
{
    // Total candidates discovered: 1
    // Valid: 0, Skipped: 1
    // Format: Index | FullyQualifiedName | Status | SkipReason

    // 0: AsyncOnExitContinueMachine
    //     status=SKIPPED
    //     reason=No [StateMachine] attribute

    /*
     * End of discovery dump
     */
}
