// <auto-generated/>
// Generator Build: 2025-09-18 18:46:56 UTC
#nullable enable
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using FastFsm.Contracts;
using FastFsm.Runtime;
using Microsoft.Extensions.Logging;

public interface ISimpleMachine : IStateMachineSync<MyState, MyTrigger> { }

public partial class SimpleMachine : StateMachineBase<MyState, MyTrigger>, ISimpleMachine {
    private readonly string _instanceId = Guid.NewGuid().ToString();

    private readonly ILogger<SimpleMachine>? _logger;

    // State and trigger name arrays for zero-allocation logging
    private static readonly string[] s_stateNames = new[] { "A", "B" };
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private static string NameOf(MyState s) {
        int index = (int)s;
        return (index >= 0 && index < s_stateNames.Length) ? s_stateNames[index] : (index == -1 ? "<root>" : s.ToString());
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    partial void OnActionException(string context, System.Exception ex);

    public SimpleMachine(MyState initialState, ILogger<SimpleMachine>? logger = null) : base(initialState) {
        _logger = logger;
    }

    public override void Start() {
        if (IsStarted) return;

        base.Start();

        SimpleMachineLog.MachineStarted(_logger, _instanceId, _currentState.ToString());
    }

    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    protected override bool TryFireInternal(MyTrigger trigger, object? payload) {
        return false; // No transitions defined
    }
    /// <summary>
    /// Checks if the specified trigger can be fired in the current state (runtime evaluation including guards)
    /// </summary>
    /// <param name="trigger">The trigger to check</param>
    /// <returns>True if the trigger can be fired, false otherwise</returns>
    [System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    protected override bool CanFireInternal(MyTrigger trigger) {
        switch (_currentState) {
            default: return false;
        }
    }

    /// <summary>
    /// Gets the list of triggers that can be fired in the current state (runtime evaluation including guards)
    /// </summary>
    /// <returns>List of triggers that can be fired in the current state</returns>
    protected override System.Collections.Generic.IReadOnlyList<MyTrigger> GetPermittedTriggersInternal() {
        switch (_currentState) {
            case MyState.A: return System.Array.Empty<MyTrigger>();
            case MyState.B: return System.Array.Empty<MyTrigger>();
            default: return System.Array.Empty<MyTrigger>();
        }
    }

}

/*
====== PARSER COMPARISON DEBUG INFO ======
Original StateMachineParser Model:
{
  "Namespace": "",
  "ClassName": "SimpleMachine",
  "ContainerClasses": [],
  "StateType": "MyState",
  "TriggerType": "MyTrigger",
  "Transitions": [],
  "States": {
    "A": {
      "Name": "A",
      "OrdinalValue": 0,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    },
    "B": {
      "Name": "B",
      "OrdinalValue": 1,
      "OnEntrySignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnExitSignature": {
        "IsAsync": false,
        "IsVoidEquivalent": false,
        "IsBoolEquivalent": false,
        "HasParameterless": false,
        "HasPayloadOnly": false,
        "HasTokenOnly": false,
        "HasPayloadAndToken": false
      },
      "OnEntryIsAsync": false,
      "OnExitIsAsync": false,
      "OnEntryExpectsPayload": false,
      "OnEntryHasParameterlessOverload": false,
      "OnExitExpectsPayload": false,
      "OnExitHasParameterlessOverload": false,
      "ChildStates": [],
      "IsComposite": false,
      "History": 0,
      "IsInitial": false
    }
  },
  "GenerationConfig": {
    "HasOnEntryExit": false,
    "HasPayload": false,
    "HasExtensions": false,
    "IsAsync": false,
    "TreatCancellationAsFailure": false
  },
  "TriggerPayloadTypes": {},
  "GenerateLogging": true,
  "GenerateDependencyInjection": false,
  "EmitStructuralHelpers": false,
  "ContinueOnCapturedContext": false,
  "ParentOf": {},
  "ChildrenOf": {},
  "Depth": {},
  "InitialChildOf": {},
  "HistoryOf": {},
  "HierarchyEnabled": false,
  "HasHierarchy": false,
  "UsedEnumOnlyFallback": true
}

FluentParser Model:
{}
==========================================
*/